server:
  port: 6666

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    password: 123456
    username: HR
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filter: stat
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: cn.gson.boot02106.model.pojos
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true
